### ISSUE TITLE
A SMS extension

### ISSUE THREAD

**Issue by discoveryhkuser** [savaka2/scratch-extensions-directory#35]
* JS link: https://discoveryhk.github.io/sms-server/scratch/send_SMS.js
* Author: discoveryHK
* Description: 
ScratchX SMS message support
Optional stuff: Android App: https://play.google.com/store/apps/details?id=com.discoveryhk.smsgatesrv
* Code on GitHub (url should contain "/blob/") (or Gist): https://discoveryhk.github.io/sms-server/scratch/send_SMS.js
* Demo project URL (preferably on GitHub Pages): https://github.com/discoveryhk/sms-server/wiki/Scratch-Support

**Comment by savaka2** [comment]
I don't have a button for "Android App," I did however add a docs URL to https://www.discoveryhk.com/ which seems to then direct the user to the Android app
Also, that is not a demo project URL, it seems to be some sort of documentation, but the documentation is already https://www.discoveryhk.com/ so idk how to add it

**Comment by discoveryhk** [comment]
Dear Sam,

Thanks for your mail. Revised the description as below:

* JS link: https://discoveryhk.github.io/sms-server/scratch/send_SMS.js
* Author: discoveryHK
* Description: ScratchX SMS message support
Optional stuff: In order to send Real SMS message under ScratchX, we need a
SMS Gateway Server. Here, we use an Android App:
https://play.google.com/store/apps/details?id=com.discoveryhk.smsgatesrv
More detail can be find on
https://github.com/discoveryhk/sms-server/wiki/Scratch-Support
* Code on GitHub (url should contain "/blob/") (or Gist):
https://discoveryhk.github.io/sms-server/scratch/send_SMS.js
* Demo project URL (preferably on GitHub Pages):
https://discoveryhk.github.io/sms-server/scratch/SMS Notification today
temp.sbx

Thank you.

**Comment by savaka2** [comment]
oh, "Optional stuff" is not actually a field it just indicates that the 2 fields below (GitHub, Demo) are optional and not required to fill out, so idk what to do with the extended description and URLs included there

**Comment by discoveryhk** [comment]
Dear Sam,

Sorry for the mistake. The optional message should be on the description.
Attached the revised detail:

* JS link: https://discoveryhk.github.io/sms-server/scratch/send_SMS.js
* Author: discoveryHK
* Description: In order to send real SMS message under ScratchX, we need a
SMS Gateway Server. Here, we use an Android App:
https://play.google.com/store/apps/details?id=com.discoveryhk.smsgatesrv
It is a real SMS Gateway with password protect, temporary disable SMS
function and logging (Suitable for demo in classroom). More detail can be
find on https://github.com/discoveryhk/sms-server/wiki/Scratch-Support
Optional stuff:
* Code on GitHub (url should contain "/blob/") (or Gist):
https://discoveryhk.github.io/sms-server/scratch/send_SMS.js
* Demo project URL (preferably on GitHub Pages):
https://discoveryhk.github.io/sms-server/scratch/SMS Notification today
temp.sbx

Thanks again.

**Comment by discoveryhk** [comment]
Dear Sam,

After a deep thinking, I think we need to add a message "The SMS is not a
free service" to the user. Revised the detail as below:

* JS link: https://discoveryhk.github.io/sms-server/scratch/send_SMS.js
* Author: discoveryHK
* Description: *** The SMS service is NOT A FREE service, Please check your
mobile service company. ***
In order to send real SMS message under ScratchX, we need a SMS Gateway
Server. Here, we use an Android App: https://play.google.com/store/
apps/details?id=com.discoveryhk.smsgatesrv
It is a real SMS Gateway with password protect, temporary disable SMS
function and logging (Suitable for demo in classroom). More detail can be
find on https://github.com/discoveryhk/sms-server/wiki/Scratch-Support

Optional stuff:
* Code on GitHub (url should contain "/blob/") (or Gist):
https://discoveryhk.github.io/sms-server/scratch/send_SMS.js
* Demo project URL (preferably on GitHub Pages):
https://discoveryhk.github.io/sms-server/scratch/SMS Notification today
temp.sbx

Sorry for the inconvenience I made.

**Comment by savaka2** [comment]
the demo project URL doesn't load in ScratchX (maybe because there are spaces in it?)

**Comment by discoveryhk** [comment]
Dear Sam,

Revised the demo project URL for reference, thank you.

* JS link: https://discoveryhk.github.io/sms-server/scratch/send_SMS.js
* Author: discoveryHK
* Description: *** The SMS service is NOT A FREE service, Please check your
mobile service company. ***
In order to send real SMS message under ScratchX, we need a SMS Gateway
Server. Here, we use an Android App: https://play.google.com/
store/apps/details?id=com.discoveryhk.smsgatesrv
It is a real SMS Gateway with password protect, temporary disable SMS
function and logging (Suitable for demo in classroom). More detail can be
find on https://github.com/discoveryhk/sms-server/wiki/Scratch-Support

Optional stuff:
* Code on GitHub (url should contain "/blob/") (or Gist):
https://discoveryhk.github.io/sms-server/scratch/send_SMS.js
* Demo project URL (preferably on GitHub Pages):
https://discoveryhk.github.io/sms-server/scratch/SMS_Notification_today_temp.sbx

**Comment by savaka2** [comment]
Maybe it isn't because of the spaces, I am unsure why the demo doesn't load in ScratchX
this is what I tried: http://scratchx.org/?url=https://discoveryhk.github.io/sms-server/scratch/SMS_Notification_today_temp.sbx

**Comment by discoveryhkuser** [comment]
Dear Sam,

Thanks for your remind. The demo is working now. The problem is the first I
create on the Github was the "project", it should be "organisation".
Finally, I rename the Github user, create 2 organisations ...

Thank you.

**Comment by savaka2** [comment]
added
